#training
max_iters: 2000 #00 #180 #00
normalise_targets: True
test_frequency: 1000 # 1000
save_model: True
hard_periodicity: True
c: 5

#Models
model:
  name: RFF #or RFF/SIREN/WIRES
  hidden_nlayers: 4
  hidden_width: 256
  scale: 1
  skip: False
  ## RFF specific
  mapping_size: 256
  activation: tanh
  modified_mlp: True #True # if you have a seperate encoder for the spatial and temporal inputs.
  linear: HE # RWF # HE # Glorot # RWF RWF does not work with SIREN
  # RWF Specific
  mean: 1
  std: 0.1

# Lambda values in the loss
validation_loss: mse
losses:
  mse:
    report: True
    bs: 64
    loss_balancing: True #wether to be included in loss balancing
  pde:
    report: True
    log: True
    lambda: 1.e-1
    temporal_causality: True
    bs: 8192 # 8192 #16384 # 65536 #32768 # 8192 # √ # powers of 2 only
    method: pde
    loss_balancing: True #wether to be included in loss balancing
  # periodicity:
  #   report: False
  #   lambda: 1.e-1
  #   temporal_causality: True
  #   bs: 8192 # 8192 # 16384 # 32768 # powers of 2 only
  #   method: periodicity
  # spatial_grad:
  #   report: True
  #   log: True
  #   lambda: 1000000
  #   temporal_causality: True
  #   bs: 8192 # 8192 #16384 # 65536 #32768 # 8192 # √ # powers of 2 only
  #   method: spatial_gradient
  #   loss_balancing: False #wether to be included in loss balancing




# learning schemes
temporal_causality:
  M: 16 # powers of 2 only
  eps: 8.e-3
  step: 1 #update

regularisation:
  L1:
    bs: 8192
    method: L1
    scalar: 1.e-1
    temporal_causality: True

# Loss balancing
relobralo:
  status: False
  T: 1.
  alpha: 0.999
  rho: 0.5
  step: 100

self_adapting_loss_balancing:
  status: True
  alpha: 0.9
  step: 1000 #1000 #update


early_stopping:
  status: False
  ignore_first: 5
  patience: 20
  value: 0.0001

# optimizers
lr: 1.e-3
eps: 1.e-8 #adam precision
clip_gradients: True

learning_rate_decay:
  status: True
  step: 2000
  gamma: 0.98 # 0.9

cosine_anealing:
  status: False
  min_eta: 0
  step: 500

optuna:
  patience: 10000
  trials: 100
